// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Q70-lTbLsl9xf48K-U7bewP-0wc2trA',
    appId: '1:590816446709:web:b2b7820b76716805f29dbc',
    messagingSenderId: '590816446709',
    projectId: 'recipe-app-a8b43',
    authDomain: 'recipe-app-a8b43.firebaseapp.com',
    storageBucket: 'recipe-app-a8b43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWeM5F6_lct5ktQU_AYhB3rEs2IiMjFOw',
    appId: '1:590816446709:android:b7b8eefa1618cc02f29dbc',
    messagingSenderId: '590816446709',
    projectId: 'recipe-app-a8b43',
    storageBucket: 'recipe-app-a8b43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsDEr2KzdZqVBdTvS1W20fMQGKFI_O_rs',
    appId: '1:590816446709:ios:05d1dc36c4e169b6f29dbc',
    messagingSenderId: '590816446709',
    projectId: 'recipe-app-a8b43',
    storageBucket: 'recipe-app-a8b43.appspot.com',
    iosBundleId: 'com.example.recipeapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsDEr2KzdZqVBdTvS1W20fMQGKFI_O_rs',
    appId: '1:590816446709:ios:29904da0c69f4971f29dbc',
    messagingSenderId: '590816446709',
    projectId: 'recipe-app-a8b43',
    storageBucket: 'recipe-app-a8b43.appspot.com',
    iosBundleId: 'com.example.recipeapp.RunnerTests',
  );
}
